export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_ALERT = 'CLEAR_ALERT'
export const SET_LAST_URL = 'SET_LAST_URL'
export const SET_SLIDER = 'SET_SLIDER'
//USER
export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

//AUTHENTICATION
export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'

// ROLES

export const GET_ROLES = 'GET_ROLES'

export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS'

export const CREATE_ROLE_ERROR = 'CREATE_ROLE_ERROR'

export const DELETE_ROLES_SUCCESS = 'DELETE_ROLES_SUCCESS'

export const DELETE_ROLES_DELETE = 'DELETE_ROLES_DELETE'

export const CREATE_COMPANY_SUCCESS = 'CREATE_COMPANY_SUCCESS'

export const GET_COMPANIES = 'GET_COMPANIES'

export const UPDATE_OFFICES_SUCCESS = 'UPDATE_OFFICES_SUCCESS'
