export const DISPLAY_ALERT = 'SHOW_ALERT'
export const HANDLE_CHANGE = 'HANDLE_CHANGE'
export const CLEAR_ALERT = 'CLEAR_ALERT'
export const SET_LAST_URL = 'SET_LAST_URL'

//USER
export const UPDATE_USER_BEGIN = 'UPDATE_USER_BEGIN'
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR'

//ALERT

export const CUSTOM_ALERT = 'CUSTOM_ALERT'

//PRODUCTS
export const GET_SINGLE_PRODUCT_BEGIN = 'GET_SINGLE_PRODUCT_BEGIN'
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS'
export const GET_SINGLE_PRODUCT_ERROR = 'GET_SINGLE_PRODUCT_ERROR'

//PRODUCTS FILTERS

export const GET_FILTERS = 'GET_FILTERS'
export const CLEAR_FILTERS = 'CLEAR_FILTERS'

//AUTHENTICATION
export const REGISTER_USER_BEGIN = 'REGISTER_USER_BEGIN'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR'

export const LOGIN_USER_BEGIN = 'LOGIN_USER_BEGIN'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR'

export const LOGOUT_USER = 'LOGOUT_USER'

//CART
export const ADD_CART_BEGIN = 'ADD_CART_BEGIN'
export const ADD_CART_ERROR = 'ADD_CART_ERROR'
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS'

export const CHANGE_CART_QUANTITY = 'CHANGE_CART_QUANTITY'

export const CALC_CART_TOTAL = 'CALC_CART_TOTAL'

//ADDRESSES
//ADD
export const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS'
export const ADD_ADDRESS_ERROR = 'ADD_ADDRESS_ERROR'

//GET
export const GET_ALL_ADDRESSES_BEGIN = 'GET_ALL_ADDRESSES_BEGIN'
export const GET_ALL_ADDRESSES_SUCCESS = 'GET_ALL_ADDRESSES_SUCCESS'
export const GET_ALL_ADDRESSES_ERROR = 'GET_ALL_ADDRESSES_ERROR'

export const SET_DELIVERY_ADDRESS = 'SET_DELIVERY_ADDRESS'

// RECIPE

export const ADD_RECIPE_BEGIN = 'ADD_RECIPE_BEGIN'
export const ADD_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS'
export const ADD_RECIPE_ERROR = 'ADD_RECIPE_ERROR'

//STRIPE
export const SET_CLIENT_SECRET = 'SET_CLIENT_SECRET'
export const GET_PUBLISHABLE_KEY_BEGIN = 'GET_PUBLISHABLE_KEY_BEGIN'
export const GET_PUBLISHABLE_KEY_SUCCESS = 'GET_PUBLISHABLE_KEY_SUCCESS'
export const GET_PUBLISHABLE_KEY_ERROR = 'GET_PUBLISHABLE_KEY_ERROR'

export const GET_ORDERS_BEGIN = 'GET_ORDERS_BEGIN'
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS'
export const GET_ORDERS_ERROR = 'GET_ORDERS_ERROR'
